services:
  postgres:
    container_name: postgres-sql-supplier-data
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: supplier_database
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-supplier
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-supplier-mail
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1026:1025
networks:
  spring-supplier:
    driver: bridge

volumes:
  postgres:
    driver: local